"""empty message

Revision ID: 26a4a7c49a07
Revises: a6df08232ffd
Create Date: 2020-11-14 01:37:56.218559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a4a7c49a07'
down_revision = 'a6df08232ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('ip', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'ip')
    # ### end Alembic commands ###
